# Generated by Django 4.0.10 on 2025-03-01 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_recipe"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="time_minutes",
            new_name="time_in_minutes",
        ),
    ]
